apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: devoteam_user
        - name: MYSQL_ROOT_PASSWORD
          value: qwerty1234
        image: mysql:8
        name: mysqldb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
